const data = {
  products: [
    {
      name: 'Bicycle blue deck of cards',
      slug: 'bicycle-bluedeck-cards',
      category: 'Cards',
      image: '/images/p1.jpg',
      price: 2,
      countInStock: 1500,
      brand: 'Bicycle',
      rating: 4.9,
      numReviews: 100,
      description: 'Great for everyday card magic',
    },
    {
      name: 'Bicycle red deck of cards',
      slug: 'bicycle-reddeck-cards',
      category: 'Cards',
      image: '/images/p2.jpg',
      price: 2,
      countInStock: 1500,
      brand: 'Bicycle',
      rating: 4.9,
      numReviews: 100,
      description: 'Great for everyday card magic',
    },
    {
      name: 'Batman deck of cards',
      slug: 'batman-cards',
      category: 'Trick Cards',
      image: '/images/p4.jpg',
      price: 10,
      countInStock: 120,
      brand: 'Theory11',
      rating: 4.7,
      numReviews: 34,
      description: 'Great visual cards',
    },
    {
      name: 'Hexawand magic wand',
      slug: 'hexawand',
      category: 'Props',
      image: '/images/p5.jpg',
      price: 35,
      countInStock: 98,
      brand: 'VanishingInc',
      rating: 4.3,
      numReviews: 23,
      description: 'Great for kids shows',
    },
  ],
};

export default data;
